# =============================================================================
# JacobPEvans Standard Labels
# =============================================================================
# Canonical label set for all repositories.
# Synced via EndBug/label-sync GitHub Action.
#
# Categories:
#   type:*     - What kind of change (aligns with semantic versioning)
#   priority:* - Urgency level
#   size:*     - Effort estimation
#   ai:*       - AI workflow state
#   (ungrouped) - Triage/admin labels
#
# Requirements (enforced via issue templates):
#   - At least one type:* label
#   - Exactly one priority:* label
#   - Exactly one size:* label
# =============================================================================

# -----------------------------------------------------------------------------
# TYPE LABELS - What kind of change is this?
# -----------------------------------------------------------------------------
- name: "type:bug"
  color: "d73a4a"
  description: "Something isn't working (semver: PATCH)"

- name: "type:feature"
  color: "0075ca"
  description: "New feature or request (semver: MINOR)"

- name: "type:breaking"
  color: "b60205"
  description: "Breaking changes (semver: MAJOR)"

- name: "type:docs"
  color: "0075ca"
  description: "Documentation only changes"

- name: "type:chore"
  color: "fef2c0"
  description: "Maintenance tasks, dependencies, tooling"

- name: "type:ci"
  color: "1d76db"
  description: "CI/CD pipeline changes"

- name: "type:test"
  color: "00ff00"
  description: "Adding or correcting tests"

- name: "type:refactor"
  color: "fbca04"
  description: "Code change that neither fixes a bug nor adds a feature"

- name: "type:perf"
  color: "ff9800"
  description: "Performance improvements"

# -----------------------------------------------------------------------------
# PRIORITY LABELS - How urgent is this?
# -----------------------------------------------------------------------------
- name: "priority:critical"
  color: "b60205"
  description: "Urgent - requires immediate attention"

- name: "priority:high"
  color: "d93f0b"
  description: "High priority - should be addressed soon"

- name: "priority:medium"
  color: "fbca04"
  description: "Medium priority - normal workflow"

- name: "priority:low"
  color: "0e8a16"
  description: "Low priority - address when time permits"

# -----------------------------------------------------------------------------
# SIZE LABELS - How much effort is this?
# -----------------------------------------------------------------------------
- name: "size:xs"
  color: "c2e0c6"
  description: "Extra small - trivial change, <1 hour"

- name: "size:s"
  color: "a2d9a2"
  description: "Small - simple change, 1-4 hours"

- name: "size:m"
  color: "7ec87e"
  description: "Medium - moderate effort, 1-2 days"

- name: "size:l"
  color: "5cb85c"
  description: "Large - significant work, 3-5 days"

- name: "size:xl"
  color: "3d8b3d"
  description: "Extra large - major effort, 1+ weeks"

# -----------------------------------------------------------------------------
# AI WORKFLOW LABELS
# -----------------------------------------------------------------------------
- name: "ai:created"
  color: "fbca04"
  description: "AI-generated issue - requires human approval (no ai:ready = not approved)"

- name: "ai:ready"
  color: "0099ff"
  description: "Human-approved and ready for any AI agent to implement"

# -----------------------------------------------------------------------------
# TRIAGE LABELS - Administrative
# -----------------------------------------------------------------------------
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"
