# SOPS configuration for terraform-proxmox
#
# Age key generation (one-time setup):
#   age-keygen -o ~/.config/sops/age/keys.txt
#
# The public key below must match your age key.
# Replace the placeholder with your actual age public key.

creation_rules:
  - path_regex: secrets\.enc\.yaml$
    age: "age1y0jvtlp2ac8fwwvh2nzm88ehye74jlseywjrjcjqll7u8vycsedq788tp9"
