name: Release Please

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    permissions:
      contents: read
      pull-requests: write
    uses: JacobPEvans/.github/.github/workflows/_release-please.yml@bb06295fe1aa5a88bcbc211e98cd1d53bf751df8 # main
    secrets:
      GH_ACTION_JACOBPEVANS_APP_ID: ${{ secrets.GH_ACTION_JACOBPEVANS_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
